### ISSUE TITLE
Won't compile without updating packages

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/todo-app#20]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Won't compile/run with current dependency version

## Details

```
$ npm run develop

> webpack-dev-server --config webpack.config.develop.js --open

/workspace/evergreen/todo-app/node_modules/webpack-cli/bin/config-yargs.js:89
describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/workspace/evergreen/todo-app/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/workspace/evergreen/todo-app/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

```

**Comment by hutchgrant** [comment]
problem was fixed by updating to webpack-cli@3.1.1
